### ISSUE TITLE
Test case for grants

### ISSUE THREAD

**Issue by kygrantwriter** [fcps/example-use-for-grants#1]
This seems fairly straightforward and easy.

**Comment by bb-fcps** [comment]
@kygrantwriter it is.

**Comment by bb-fcps** [comment]
@kygrantwriter Click on the little icon next to the plus symbol at the top of the page, then click on settings.  Once you're in settings click on security and there will be something that mentions setting up two-factor authentication.  You'll want to set that up.  It's basically a way that the application can remain fairly secure.

**Comment by wbuchanan** [comment]
@kygrantwriter this is my personal account that has tons of code, presentations, things that I started working on but didn't get to wrap up, etc...
